### ISSUE TITLE
Incomplete code

### ISSUE THREAD

**Issue by nformoso** [tdebatty/php-clustering#2]
Hello Thibault,
There's some lacking code in this repository.

**From \webd\clustering\GMeans**
`$X_vect = new \webd\vectors\Vector($X);`
But **\webd\vectors\Vector** Doesn't exists.

The same issue within RnPoints.php,
`class RnPoint extends \webd\vectors\Vector implements iPoint`

Regards

**Comment by tdebatty** [comment]
Hi,

It's part of composer package webd/vector

https://github.com/tdebatty/php-clustering/blob/f67d77c6dec183b25a1b0e551f4ef56c86684e60/composer.json#L6

https://packagist.org/packages/webd/vectors

https://github.com/tdebatty/php-vector-matrix

**Comment by tdebatty** [comment]
My guess is you didn't install the library with composer, hence the dependencies are not installed...

Best regards,

**Comment by nformoso** [comment]
You're right! Sorry.
